"use client";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import { setupTokenRefresh } from '../utils/auth';
import { useEffect, useState } from 'react';


const inter = Inter({ subsets: ["latin"] });
export const datos_prueba = true;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    setupTokenRefresh();
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

